### ISSUE TITLE
Persist doesn't work with Effector "^21.7.2" and React "^17.0.1"

### ISSUE THREAD

**Issue by yak0v13v** [MrFranke/effector-persist#5]
Argument of type 'import("/Users/work/VS projects/adminpanel/node_modules/effector/index").Store<State>' is not assignable to parameter of type 'import("/Users/work/VS projects/adminpanel/node_modules/effector-persist/node_modules/effector/index").Store<State>'.
  Property '[Symbol.observable]' is missing in type 'import("/Users/work/VS projects/adminpanel/node_modules/effector/index").Store<State>' but required in type 'import("/Users/work/VS projects/adminpanel/node_modules/effector-persist/node_modules/effector/index").Store<State>'.ts(2345)
index.d.ts(170, 3): '[Symbol.observable]' is declared here.

**Comment by mbaroukh** [comment]
Same error here but when you take the source in your project it works ...
Don't understand.

https://github.com/MrFranke/effector-persist/blob/master/src/index.ts

**Comment by azinit** [comment]
Still actual!)

**Comment by AndrewEastwood** [comment]
seems this repo is no longer maintained ...

**Comment by MrFranke** [comment]
Effector version was updated! Now it's working with new latest effector and react.

Really sorry for long answer. I didn't think anyone was using it.
